#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

#define SERVER_MUTEX _T("SERVER_MUTEX")

typedef enum {
	OFF,
	DEMO,
	INDIVIDUAL,
	COMPETITIVE
} GameState;

typedef enum {
	START,
	STREET,
	FINISH
} LaneType;

typedef enum {
	RIGHT,
	LEFT,
	FRONT,
	BACK,
	STOP
} Direction;

//LOGIC
#define TRUE 1
#define FALSE 0


//ERRORS
#define SUCCESS 0
#define ERROR_MULTIPLE_INSTANCES_RUNNING 1
#define ERROR_UNKNOWN_ARGUMENT 2
#define ERROR_INVALID_ARGUMENTS_QUANTITY 3
#define ERROR_INVALID_NUMBER_OF_LANES 4
#define ERROR_INVALID_SPEED 5
#define ERROR_INVALID_KEY_SPEED 6
#define ERROR_INVALID_KEY_NUMBER_OF_LANES 7
#define ERROR_CANT_OPEN_KEY 8
#define ERROR_CANT_CREATE_KEY 9
#define ERROR_CANT_SET_KEY 10
#define ERROR_SUCCESS_COMMAND_QUIT 11

//REGISTRY
#define KEYPATH _T("SOFTWARE\\Frogger\\")
#define SPEED_KEY_NAME _T("SPEED")
#define LANES_KEY_NAME _T("NUMBEROFLANES")

// SERVER DATA
#define SPEED_MIN 5
#define SPEED_MAX 120
#define SPEED_STOPPED 0

#define NUMBER_OF_LANES_STR TEXT("-l")
#define NUMBER_OF_LANES_MIN 1
#define NUMBER_OF_LANES_MAX 8
#define STARTLINE_DEFAULT 1
#define FINISHLINE_DEFAULT 1
#define LANES_MAX (STARTLINE_DEFAULT+NUMBER_OF_LANES_MAX+FINISHLINE_DEFAULT)

//NUMBER OF COLUMNS IN THE LANES
#define LANES_LENGTH 20

//CARS
#define CARS_MIN 0
#define CARS_MAX (LANES_LENGTH*LANES_MAX)
#define CARS_DEFAULT CARS_MIN

//FROGS
#define FROGS_MAX 2
#define FROGS_INDIVIDUAL 1
#define FROGS_COMPETITIVE 2
#define PLAYER1 _T("PLAYER 1")
#define PLAYER2 _T("PLAYER 2")
#define PLAYER_NAME_SIZE 128

//OBSTACLES
#define OBSTACLES_MAX (LANES_LENGTH*LANES_MAX)

//LIVES
#define LIVES_MAX 3
#define LIVES_DEFAULT LIVES_DEFAULT

//GAMES
#define GAME_DEMO _T("DEMO")
#define GAME_INDIVIDUAL _T("INDIVIDUAL")
#define GAME_COMPETITIVE _T("COMPETITIVE")

//COMMANDS
#define SIZEOF_SERVERCMD 128
#define COMMAND_QUIT _T("QUIT\n")
#define COMMAND_DEMO _T("DEMO\n")
#define COMMAND_SUSPEND _T("SUSPEND\n")
#define COMMAND_RESUME _T("RESUME\n")
#define COMMAND_RESTART _T("RESTART\n")
#define COMMAND_EXIT _T("EXIT\n")
#endif